version: '2.1'

services:
  gateway:
    image: gateway:v1
    hostname: gateway
    ports:
      - "8080:8080"
  config:
    image: config:v1
    hostname: config
    ports:
      - "8888:8888"
  mailer-core_1:
    image: mailer-core:v1
    ports:
      - "8081:8081"
    NOTATKA DO MNIE: MAILER CORE WIDZI CONFIG JAKO ZWYKLA APKA, NIE WIDZI GO W DOKERZE, KONTENER MAILER_CORE NIE WIDZI KONTENERA CONFIG.
DODATKOWO KONIECZNIE ZAIMPLEMENTOWAC HELATHCHECKA I ZROBIC W COMPOSE depends_on:config:condition: service_healthy
    depends_on:
      - gateway
      - config
  mailer-core_2:
    image: mailer-core:v1
    ports:
      - "8082:8081"
    depends_on:
      - gateway
      - config