version: '2.1'

services:
  gateway:
    image: gateway:v1
    hostname: gateway
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      config:
        condition: service_healthy

  config:
    image: config:v1
    hostname: config
    ports:
      - "8888:8888"
    restart: always

  mailer-core_1:
    image: mailer-core:v1
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      config:
        condition: service_healthy

  mailer-core_2:
    image: mailer-core:v1
    ports:
      - "8082:8081"
    restart: always
    depends_on:
      config:
        condition: service_healthy
  mailer-search_1:
    image: mailer-search:v1
    environment:
      TIME_DELAY: 100
    ports:
      - "8083:8081"
    depends_on:
      config:
        condition: service_healthy
  mailer-search_2:
    image: mailer-search:v1
    environment:
      TIME_DELAY: 500
    ports:
      - "8084:8081"
    depends_on:
      config:
        condition: service_healthy
