eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://gateway:8080/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
spring:
  application:
    name: gateway
zuul:
  routes:
    mailer-core:
      path: /core/**
      serviceId: mailer-core
    mailer-search:
      path: /search/**
      serviceId: mailer-search
security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
proxy:
  auth:
    routes:
      mailer-core: oauth2