eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://gateway:8080/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
spring:
  application:
    name: gateway
zuul:
  routes:
    mailer-core:
      path: /core/**
      serviceId: mailer-core