eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://gateway:8080/eureka/
instance:
  hostname: localhost
server:
  port: 8081
spring:
  application:
    name: mailer-core